# Generated by Django 3.1.4 on 2021-02-02 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_foods'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Foods',
            new_name='Food',
        ),
    ]
