# Generated by Django 3.1.4 on 2021-02-02 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_orderdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderDetails',
            new_name='OrderDetail',
        ),
    ]
